apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandlock-operator
  namespace: {{ include "sandlock.systemNamespace" . }}
  labels:
    {{- include "sandlock.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandlock-controlplane
  namespace: {{ include "sandlock.systemNamespace" . }}
  labels:
    {{- include "sandlock.labels" . | nindent 4 }}
