apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "sandlock.systemNamespace" . }}
  labels:
    {{- include "sandlock.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "sandlock.sandboxNamespace" . }}
  labels:
    {{- include "sandlock.labels" . | nindent 4 }}
    kubernetes.io/metadata.name: {{ include "sandlock.sandboxNamespace" . }}
