{{- $existingAdmin := lookup "v1" "Secret" (include "sandlock.systemNamespace" .) "sandlock-admin" -}}
{{- $adminPassword := "" -}}
{{- if $existingAdmin -}}
  {{- $adminPassword = index $existingAdmin.data "password" | b64dec -}}
{{- else -}}
  {{- $adminPassword = .Values.admin.password | default (randAlphaNum 20) -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: sandlock-admin
  namespace: {{ include "sandlock.systemNamespace" . }}
  labels:
    {{- include "sandlock.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  password: {{ $adminPassword | quote }}
---
{{- if and (not .Values.postgresql.enabled) .Values.database.url (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: sandlock-db
  namespace: {{ include "sandlock.systemNamespace" . }}
  labels:
    {{- include "sandlock.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.database.url | quote }}
{{- end }}
{{- if and .Values.masterKey (not .Values.masterKeyExistingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sandlock-master-key
  namespace: {{ include "sandlock.systemNamespace" . }}
  labels:
    {{- include "sandlock.labels" . | nindent 4 }}
type: Opaque
stringData:
  MASTER_KEY: {{ .Values.masterKey | quote }}
{{- end }}
